config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"

  resources :users, only: %i[new create]

  resources :boards, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit destroy], shallow: true
    get :bookmarks, on: :collection
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]


  resources :password_resets, only: %i[new create edit update]

  #ログインするとuser_sessionsのnewアクションにいく
  get '/login', to: 'user_sessions#new'
  #createはDBに保存もするためpostを使う
  post '/login', to: 'user_sessions#create'
  #ログアウトは
  delete '/logout', to: 'user_sessions#destroy'

  #adminページのルーティング
  namespace :admin do
    root 'dashboards#index'
    resource :dashboard, only: %i[index]
    get '/login', to: 'sessions#new', :as => :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', :as => :logout
    resources :users, only: %i[index show edit update destroy]
    resources :boards, only: %i[index show edit update destroy]
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end
end

app/views/comments/_comment.html.erb
<!-- 表示されているコメントのIDが入るように調整してください -->
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag "sample", class: "rounded-circle", width: "50", height: "50" %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.full_name %></h3>
    <%= simple_format(comment.body) %>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "#", class: 'edit-comment-link' do %>
            <i class='bi bi-pencil-fill'></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: 'delete-comment-link', data: { turbo_method: :delete, turbo_confirm: t('boards.board.confirm') } do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<!-- コメントフォーム -->
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
	    <%= f.label :body %>
	    <%= f.text_field :body, class: "form-control mb-3", rows: '4', placeholder: Comment.human_attribute_name(:body) %>
	    <%= f.submit t('defaults.post'), class: "btn btn-primary" %>
	  <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, board: @comment.board %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, board: @comment.board %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" %>