config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"

  resources :users, only: %i[new create]

  resources :boards, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit destroy], shallow: true
    get :bookmarks, on: :collection
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]


  resources :password_resets, only: %i[new create edit update]

  #ログインするとuser_sessionsのnewアクションにいく
  get '/login', to: 'user_sessions#new'
  #createはDBに保存もするためpostを使う
  post '/login', to: 'user_sessions#create'
  #ログアウトは
  delete '/logout', to: 'user_sessions#destroy'

  #adminページのルーティング
  namespace :admin do
    root 'dashboards#index'
    resource :dashboard, only: %i[index]
    get '/login', to: 'sessions#new', :as => :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', :as => :logout
    resources :users, only: %i[index show edit update destroy]
    resources :boards, only: %i[index show edit update destroy]
  end

end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t('header.login'), login_path, class: "nav-link" %>
          <%= link_to t('users.new.title'), new_user_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2019. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class:  'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    </a>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to t('header.board'), "#", class: "nav-link dropdown-toggle", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to t('header.board_index'), boards_path, class: 'dropdown-item' %>
            <%= link_to t('header.create_board'), new_board_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to t('header.bookmark_index'), bookmarks_boards_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <!-- data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true' }, aria: { expanded: 'false' } -->
          <%= link_to "#", class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true' }, aria: { expanded: 'false' }, id:'header-profile' do %>
            <%= image_tag current_user.avatar_url, class: 'rounded-circle mr15', width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'><%= current_user.decorate.full_name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to t('header.profile'), profile_path, class: 'dropdown-item' %>
            <%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete }, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>