config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"

  resources :users, only: %i[new create]

  resources :boards, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit destroy], shallow: true
    get :bookmarks, on: :collection
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]


  resources :password_resets, only: %i[new create edit update]

  #ログインするとuser_sessionsのnewアクションにいく
  get '/login', to: 'user_sessions#new'
  #createはDBに保存もするためpostを使う
  post '/login', to: 'user_sessions#create'
  #ログアウトは
  delete '/logout', to: 'user_sessions#destroy'

  #adminページのルーティング
  namespace :admin do
    root 'dashboards#index'
    resource :dashboard, only: %i[index]
    get '/login', to: 'sessions#new', :as => :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', :as => :logout
    resources :users, only: %i[index show edit update destroy]
    resources :boards, only: %i[index show edit update destroy]
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to boards_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, danger: t('user_sessions.destroy.success')
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= content_for :title %></h1>
      <%= form_with url: login_path, local: true do |form| %>
        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password, class: "form-label" %>
          <%= form.text_field :password, class: "form-control" %>
        </div>
        <%= form.submit t('user_sessions.new.login'), class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to t('.to_register_page'), new_user_path %>
        <%= link_to t('.password_forget'), new_password_reset_path %>
      </div>
    </div>
  </div>
</div>