config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"

  resources :users, only: %i[new create]

  resources :boards, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit destroy], shallow: true
    get :bookmarks, on: :collection
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]


  resources :password_resets, only: %i[new create edit update]

  #ログインするとuser_sessionsのnewアクションにいく
  get '/login', to: 'user_sessions#new'
  #createはDBに保存もするためpostを使う
  post '/login', to: 'user_sessions#create'
  #ログアウトは
  delete '/logout', to: 'user_sessions#destroy'

  #adminページのルーティング
  namespace :admin do
    root 'dashboards#index'
    resource :dashboard, only: %i[index]
    get '/login', to: 'sessions#new', :as => :login
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', :as => :logout
    resources :users, only: %i[index show edit update destroy]
    resources :boards, only: %i[index show edit update destroy]
  end

end

app/views/admin/shared/_footer.html.erb
<footer>
  <p class='mt-3 text-muted'>Copyright &copy; 2019 RUNTEQ.</p>
</footer>

app/views/admin/shared/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to admin_root_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" do %>
    <%= image_tag "bootstrap-logo", alt: "RUNTEQ Logo", class: "brand-image img-circle elevation-3", style: "opacity: .8", width: '33px', height: '28px' %>
    RUNTEQ
  <% end %>
  <div class="w-100">
    <button class="navbar-toggler d-none d-md-block" type="button" id='toggleSidebar'>
      <span class="navbar-toggler-icon"></span>
    </button>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <%= link_to t('header.logout'), admin_logout_path, data: { turbo_method: :delete }, local: true, class: 'nav-link px-3' %>
    </div>
  </div>
</header>

app/views/admin/shared/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link #{active_if('admin/users')}" do %>
          <i class="bi bi-file-earmark"></i>
          <%= t('admin.users.index.title') %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_boards_path, class: "nav-link #{active_if('admin/boards')}" do %>
          <i class="bi bi-person"></i>
          <%= t('admin.boards.index.title') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>